# Generated by Django 5.0.7 on 2025-03-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlier_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThyroidCancerData',
            new_name='mytable',
        ),
    ]
